
import 'package:to_do_flutter/to-do/models/Task.dart';
import 'package:to_do_flutter/to-do/models/TaskDao.dart';

class TaskServices {

  Future<int> insertNewTask(Task task) async {
    if (task.name == null) {
      throw Exception('A To-Do List must have a name');
    }
    if (task.uid != null) {
      throw Exception('When inserting a To-Do List the uid must be null');
    }
    if (task.toDoUid == null) {
      throw Exception('A Task must belong to a to-do list');
    }
    return TaskDao.insert(task, autoGeneratedUid: true);
  }

  Future<List<Task>> getAllTasksFromTodo(int toDoUid) async {
    return TaskDao.getAllTasksFromToDoList(toDoUid);
  }

}